// TODO: Think about using bitwise operations:
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
const neighborsByType = [{
  id: 1,
  toTop: false,
  toRight: false,
  toBottom: true,
  toLeft: true
}, {
  id: 2,
  toTop: true,
  toRight: true,
  toBottom: false,
  toLeft: false
}, {
  id: 3,
  toTop: true,
  toRight: false,
  toBottom: false,
  toLeft: true
}, {
  id: 4,
  toTop: false,
  toRight: true,
  toBottom: true,
  toLeft: false
}, {
  id: 5,
  toTop: false,
  toRight: true,
  toBottom: false,
  toLeft: true
}, {
  id: 6,
  toTop: true,
  toRight: false,
  toBottom: true,
  toLeft: false
}, {
  id: 7,
  toTop: false,
  toRight: false,
  toBottom: false,
  toLeft: false
}, {
  id: 8,
  toTop: true,
  toRight: false,
  toBottom: true,
  toLeft: true
}, {
  id: 9,
  toTop: false,
  toRight: true,
  toBottom: false,
  toLeft: false
}, {
  id: 10,
  toTop: false,
  toRight: true,
  toBottom: false,
  toLeft: false
}, {
  id: 11,
  toTop: false,
  toRight: true,
  toBottom: false,
  toLeft: false
}, {
  id: 12,
  toTop: true,
  toRight: false,
  toBottom: false,
  toLeft: false
}, {
  id: 13,
  toTop: false,
  toRight: false,
  toBottom: false,
  toLeft: false
}, {
  id: 14,
  toTop: false,
  toRight: false,
  toBottom: false,
  toLeft: false
}, {
  id: 15,
  toTop: false,
  toRight: false,
  toBottom: false,
  toLeft: false
}, {
  id: 16,
  toTop: false,
  toRight: false,
  toBottom: true,
  toLeft: true
}]

export default neighborsByType
